version: "3.7"
services:
  jobseeker-gw:
    build: ./src/gateways/jobseeker
    restart: always
    hostname: jobseeker-gw
    env_file:
      - .env
    ports:
      - "8080:3000"
    networks:
      - backend
      - frontend
    volumes:
      - ./src/gateways/jobseeker:/var/www/jobseeker-gw
    command: npm run start:dev

  recruiter-gw:
    build: ./src/gateways/recruiter
    restart: always
    hostname: recruiter-gw
    env_file:
      - .env
    ports:
      - "8082:3000"
    networks:
      - backend
      - frontend
    volumes:
      - ./src/gateways/recruiter:/var/www/recruiter-gw
    command: npm run start:dev  

  public:
    build: ./src/gateways/public
    restart: always
    hostname: public
    env_file:
      - .env
    ports:
      - "8081:3000"
    networks:
      - backend
      - frontend
    volumes:
      - ./src/gateways/public:/var/www/public
    command: npm run start:dev   

  quizz:
    build: ./src/microservices/quizz
    restart: always
    hostname: quizz
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - ./src/microservices/quizz:/var/www/quizz
    command: npm run start:dev

  lucky-spin:
    build: ./src/microservices/lucky-spin
    restart: always
    hostname: lucky-spin
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - ./src/microservices/lucky-spin:/var/www/lucky-spin
    command: npm run start:dev
  
  auth:
    build: ./src/microservices/auth
    restart: always
    hostname: auth
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - ./src/microservices/auth:/var/www/auth
    command: npm run start:dev

  organization:
    build: ./src/microservices/organization
    restart: always
    hostname: organization
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - ./src/microservices/organization:/var/www/organization
    command: npm run start:dev

  jobseeker:
    build: ./src/microservices/jobseeker
    restart: always
    hostname: jobseeker
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - ./src/microservices/jobseeker:/var/www/jobseeker
    command: npm run start:dev

  user:
    build: ./src/microservices/user
    restart: always
    hostname: user
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - ./src/microservices/user:/var/www/user
    command: npm run start:dev

  notification:
    build: ./src/microservices/notification
    restart: always
    hostname: notification
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - ./src/microservices/notification:/var/www/notification
    command: npm run start:dev     

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    restart: always
    networks:
      - backend
      - frontend
  
  migration-mysql:
    build: ./src/microservices/migration-mysql
    restart: always
    hostname: migration-mysql
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - ./src/microservices/migration-mysql:/var/www/migration-mysql
    command: npm run start:dev  
    
  migration-mongo:
    build: ./src/microservices/migration-mongo
    restart: always
    hostname: migration-mongo
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - ./src/microservices/migration-mongo:/var/www/migration-mongo
    command: npm run start:dev    

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass jC2qe6890UxcxPKv
    networks:
      - backend     
      
networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: infrastructure
