import { ApiPropertyOptions, Constructor } from '@joktec/core';
import { ExposeOptions } from '@joktec/utils';
import {
  ColumnOptions,
  ColumnType,
  IndexOptions,
  JoinColumnOptions,
  JoinTableOptions,
  RelationOptions,
  SelectQueryBuilder,
  ValueTransformer,
} from 'typeorm';

/**
 * Controls required/optional validation metadata.
 *
 * - `true`: add required validation.
 * - `false`: mark the property optional.
 * - `[true, message]`: add required validation with a custom message.
 */
export type RequiredOption = boolean | [boolean, string];

/**
 * Primary key generation strategies supported by the JokTec wrapper.
 *
 * `uuidv7` is generated by JokTec before insert so it can be used with
 * TypeORM drivers that do not natively generate UUID v7 values.
 */
export type PrimaryColumnStrategy = 'increment' | 'uuid' | 'uuidv7' | 'rowid' | 'identity';
export type MysqlFieldDecorator = PropertyDecorator & MethodDecorator;

type AllKeys<T> = T extends unknown ? keyof T : never;
type StrictUnionHelper<T, TAll> = T extends unknown
  ? T & Partial<Record<Exclude<AllKeys<TAll>, keyof T>, never>>
  : never;
export type StrictUnion<T> = StrictUnionHelper<T, T>;

/**
 * Main mode selector for `@Column`.
 *
 * Omit `kind` for a normal persisted TypeORM column. Use explicit kinds for
 * TypeORM special columns, relations, relation ids, tree properties, and
 * metadata-only computed getters.
 */
export type MysqlColumnKind = 'normal' | 'virtual' | 'view' | 'version' | 'relation' | 'relation-id' | 'tree';

/**
 * Virtual column mode.
 *
 * - `getter`: TypeScript getter only, no TypeORM column metadata.
 * - `sql`: TypeORM `VirtualColumn`, requires `query(alias)`.
 */
export type MysqlVirtualColumnMode = 'getter' | 'sql';

/** Relation decorator variant generated by `Column({ kind: 'relation' })`. */
export type MysqlRelationKind = 'many-to-one' | 'one-to-many' | 'one-to-one' | 'many-to-many';

/** Tree property decorator variant generated by `Column({ kind: 'tree' })`. */
export type MysqlTreePropertyKind = 'parent' | 'children' | 'level';

/** Lazy relation target resolver. Prefer `() => EntityClass` to avoid circular imports. */
export type MysqlRelationTarget = string | (() => Function);

/** TypeORM inverse-side expression used by relation decorators. */
export type MysqlRelationInverseSide<T = any> = string | ((object: T) => any);

/** TypeORM relation-id expression used by `Column({ kind: 'relation-id' })`. */
export type MysqlRelationIdFactory<T = any> = string | ((object: T) => any);

/**
 * Property-level index shortcut.
 *
 * - `true`: create an unnamed index.
 * - `string`: create a named index.
 * - `IndexOptions`: pass TypeORM index options.
 * - `{ name, options }`: create a named index with options.
 */
export type MysqlColumnIndexOptions = boolean | string | IndexOptions | { name?: string; options?: IndexOptions };

/**
 * Property-level check shortcut.
 *
 * Use table-level `Tables({ checks })` for composite checks that reference
 * multiple columns.
 */
export type MysqlColumnCheckOptions = string | { name?: string; expression: string };

/** Shared documentation, validation, transform, and visibility metadata for all column modes. */
export interface IMysqlColumnCommonOptions {
  /** Hide the field from serialized output and Swagger schema. */
  hidden?: boolean;

  /** Shortcut for `required: false`; useful when TypeORM `nullable` is not the same as DTO optionality. */
  optional?: boolean;

  /** Extra class-transformer expose options, such as groups or naming. */
  expose?: ExposeOptions;

  /** Swagger example value. */
  example?: any;

  /** Mark the generated Swagger property as deprecated. */
  deprecated?: boolean;

  /**
   * Mark the property as read-only in generated Swagger metadata.
   *
   * This mirrors Mongo `immutable` terminology for cross-package consistency.
   * It is an API/documentation hint; use TypeORM `update: false` when the
   * database column itself must be excluded from updates.
   */
  immutable?: boolean;

  /** Expose this property only for selected class-transformer groups. */
  groups?: string[];

  /** Additional property decorators that the wrapper does not model directly. */
  decorators?: PropertyDecorator[];

  /** Swagger override. Inferred wrapper values are used first, then this object overrides them. */
  swagger?: ApiPropertyOptions;

  /** Required flag or `[flag, message]` validation tuple. */
  required?: RequiredOption;

  /** Human-readable field description; also reused as Swagger description. */
  comment?: string;

  /** TypeORM nullable flag and Swagger nullable hint. */
  nullable?: boolean;
}

/** Built-in validation shortcuts applied by `@Column`. */
export interface IMysqlColumnValidationOptions {
  /**
   * Enable nested class transformation and validation.
   *
   * Pass a class constructor for array/json fields when TypeScript reflection
   * cannot infer the element type.
   */
  nested?: boolean | Constructor<any>;

  /** Apply validators to every array item. Inferred automatically for array-like columns in common cases. */
  each?: boolean;

  /** Add email validation. */
  isEmail?: boolean;

  /** Add phone validation. */
  isPhone?: boolean;

  /** Add hex color validation. */
  isHexColor?: boolean;

  /** Add URL validation. */
  isUrl?: boolean;

  /** Add integer validation. Integer column types infer this automatically. */
  isInt?: boolean;

  /** Add UUID validation. */
  isUUID?: boolean;

  /** Add object validation for JSON-like fields. */
  isObject?: boolean;

  /** Minimum string length. */
  minlength?: number;

  /** Maximum string length. */
  maxlength?: number;

  /** Alias for `minlength`. */
  minLength?: number;

  /** Alias for `maxlength`. */
  maxLength?: number;

  /** Minimum numeric value. */
  min?: number;

  /** Maximum numeric value. */
  max?: number;
}

/** Database metadata shortcuts that sit beside TypeORM column options. */
export interface IMysqlColumnDatabaseOptions {
  /** Property-level TypeORM index metadata. */
  index?: MysqlColumnIndexOptions;

  /** Property-level TypeORM check metadata. */
  check?: MysqlColumnCheckOptions;
}

/**
 * Default persisted TypeORM column.
 *
 * Use this for scalar, JSON, enum, and normal database columns. The wrapper
 * accepts regular TypeORM `ColumnOptions` plus JokTec metadata options.
 */
export interface IMysqlNormalColumnOptions
  extends ColumnOptions, IMysqlColumnCommonOptions, IMysqlColumnValidationOptions, IMysqlColumnDatabaseOptions {
  /** Optional discriminator. Omit it for normal columns. */
  kind?: 'normal';

  /** Must remain false for normal columns; use `kind: 'virtual'` for computed fields. */
  virtual?: false;

  /** Internal copy of the positional `Column(type, options)` type. */
  columnType?: ColumnType;
}

/**
 * Metadata-only TypeScript getter.
 *
 * This does not register a TypeORM column. It only applies class-transformer
 * expose metadata and Swagger metadata for computed properties.
 */
export interface IMysqlVirtualGetterColumnOptions extends IMysqlColumnCommonOptions {
  /** Virtual getter mode. */
  kind?: 'virtual';

  /** Defaults to `getter`. */
  mode?: 'getter';

  /** Legacy-friendly shorthand for getter virtual fields. */
  virtual?: true | 'getter';
}

/**
 * TypeORM SQL virtual column.
 *
 * Use this when the value is calculated by a SQL expression through
 * TypeORM `VirtualColumn`. It requires `query(alias)`.
 */
export interface IMysqlSqlVirtualColumnOptions extends IMysqlColumnCommonOptions, IMysqlColumnValidationOptions {
  kind: 'virtual';
  mode: 'sql';
  virtual?: 'sql';

  /** SQL virtual result type. Can also be passed as the first `Column(type, options)` argument. */
  type?: ColumnType;

  /** Internal copy of the positional `Column(type, options)` type. */
  columnType?: ColumnType;

  /** Whether TypeORM should select the virtual column by default. */
  select?: boolean;

  /** TypeORM hstore return mode when supported by the dialect. */
  hstoreType?: 'object' | 'string';

  /** SQL expression builder. `alias` is the current entity alias. */
  query: (alias: string) => string;

  /** TypeORM value transformer for the computed value. */
  transformer?: ValueTransformer | ValueTransformer[];
}

/** TypeORM view column wrapper with JokTec metadata. */
export interface IMysqlViewColumnOptions extends IMysqlColumnCommonOptions, IMysqlColumnValidationOptions {
  kind: 'view';

  /** Database column name in the view. */
  name?: string;

  /** TypeORM value transformer. */
  transformer?: ValueTransformer | ValueTransformer[];
}

/** TypeORM optimistic-lock version column wrapper with JokTec metadata. */
export interface IMysqlVersionColumnOptions extends IMysqlColumnCommonOptions, IMysqlColumnValidationOptions {
  kind?: 'version';

  /** Database column name. */
  name?: string;

  /** Database column type. */
  type?: ColumnType;

  /** TypeORM default value. */
  default?: any;

  /** Whether TypeORM selects this column by default. */
  select?: boolean;

  /** Property-level index metadata. */
  index?: MysqlColumnIndexOptions;

  /** Property-level check metadata. */
  check?: MysqlColumnCheckOptions;

  /** TypeORM value transformer. */
  transformer?: ValueTransformer | ValueTransformer[];
}

/**
 * Relation property wrapper.
 *
 * Generates the selected TypeORM relation decorator and optional
 * `JoinColumn`/`JoinTable`, then adds Swagger and class-transformer metadata.
 */
export interface IMysqlRelationColumnOptions extends IMysqlColumnCommonOptions {
  kind: 'relation';

  /** TypeORM relation kind. */
  relation: MysqlRelationKind;

  /** Target entity resolver. Prefer a lazy resolver: `() => UserEntity`. */
  type: MysqlRelationTarget;

  /** TypeORM inverse-side expression, for example `user => user.articles`. */
  inverseSide?: MysqlRelationInverseSide;

  /** TypeORM relation options such as cascade, eager, nullable, and onDelete. */
  relationOptions?: RelationOptions;

  /** Add `JoinColumn`. Use `true` for defaults or pass TypeORM join options. */
  joinColumn?: boolean | JoinColumnOptions | JoinColumnOptions[];

  /** Add `JoinTable`. Use `true` for defaults or pass TypeORM join-table options. */
  joinTable?: boolean | JoinTableOptions | any;

  /** Property-level index metadata for this relation property. */
  index?: MysqlColumnIndexOptions;
}

/**
 * Relation id property wrapper.
 *
 * Use this on a separate id field when the entity needs a scalar relation id
 * property generated from a relation.
 */
export interface IMysqlRelationIdColumnOptions
  extends IMysqlColumnCommonOptions, IMysqlColumnValidationOptions, IMysqlColumnDatabaseOptions {
  kind: 'relation-id';

  /** TypeORM relation-id expression, for example `article => article.author`. */
  relationId: MysqlRelationIdFactory;

  /** Optional TypeORM relation-id alias. */
  relationIdAlias?: string;

  /** Optional TypeORM relation-id query customization. */
  relationIdQuery?: (qb: SelectQueryBuilder<any>) => SelectQueryBuilder<any>;
}

/**
 * Tree property wrapper.
 *
 * Requires a matching class-level `Tables({ tree })` declaration.
 */
export interface IMysqlTreeColumnOptions extends IMysqlColumnCommonOptions {
  kind: 'tree';

  /** Tree property type: parent relation, children relation, or level column. */
  tree: MysqlTreePropertyKind;

  /** Target entity resolver for parent/children properties. */
  type?: MysqlRelationTarget;

  /** Cascade options for tree children. */
  cascade?: boolean | ('insert' | 'update' | 'remove' | 'soft-remove' | 'recover')[];

  /** Delete behavior for tree parent. */
  onDelete?: 'RESTRICT' | 'CASCADE' | 'SET NULL' | 'DEFAULT' | 'NO ACTION';
}

/**
 * Public option union for `@Column`.
 *
 * The union is intentionally strict: options from one mode should not be mixed
 * into another mode. Inline object literals get the strongest TypeScript
 * checking; for shared constants, prefer `satisfies IMysqlColumnOptions`.
 */
export type IMysqlColumnOptions = StrictUnion<
  | IMysqlNormalColumnOptions
  | IMysqlVirtualGetterColumnOptions
  | IMysqlSqlVirtualColumnOptions
  | IMysqlViewColumnOptions
  | IMysqlVersionColumnOptions
  | IMysqlRelationColumnOptions
  | IMysqlRelationIdColumnOptions
  | IMysqlTreeColumnOptions
>;

export type IMysqlColumnBuildOptions = Partial<ColumnOptions> &
  IMysqlColumnCommonOptions &
  IMysqlColumnValidationOptions & {
    kind?: MysqlColumnKind;
    virtual?: boolean | MysqlVirtualColumnMode;
    columnType?: ColumnType;
  };

/** Options for `PrimaryColumn` and `PrimaryGeneratedColumn` alias. */
export interface IMysqlPrimaryColumnOptions extends Omit<IMysqlNormalColumnOptions, 'primary' | 'nullable' | 'kind'> {
  /** Primary columns cannot be nullable. */
  nullable?: false;
}

/** Options for `TimestampColumn('create' | 'update' | 'delete')`. */
export interface IMysqlTimestampColumnOptions extends Omit<IMysqlNormalColumnOptions, 'columnType' | 'kind'> {}

/** Overload argument tuple used by the `Column` decorator implementation. */
export type ColumnDecoratorArgs = [IMysqlColumnOptions?] | [ColumnType, IMysqlColumnOptions?];

export interface RequiredResult {
  required: boolean;
  message?: string;
}
