fullnameOverride: migration-gateway

args: ['npm', 'run', 'start:prod']

extraEnvVars:
  - name: JWT_TOKEN_SECRET
    value: JWTMrJobhopSecretKey
  - name: JWT_TOKEN_EXPIRES
    value: "30"

  - name: MIGRATION_VERSION
    value: 1.1.6

    # Mongo config
    # Mongo migration
  - name: MONGODB_URL_MIGRATION
    value: mongodb+srv://jobhop:Qus7YbkpaqfIlwAI@mongodb-jobhop-prod.xbpov.mongodb.net
  - name: MONGODB_DATABASE_MIGRATION
    value: main
    # Mongo activity
  - name: MONGODB_URL_ACTIVITY
    value: mongodb+srv://jobhop:Qus7YbkpaqfIlwAI@mongodb-jobhop-prod.xbpov.mongodb.net
  - name: MONGODB_DATABASE_ACTIVITY
    value: activity
    # Mongo blog
  - name: MONGODB_URL_BLOG
    value: mongodb+srv://jobhop:Qus7YbkpaqfIlwAI@mongodb-jobhop-prod.xbpov.mongodb.net
  - name: MONGODB_DATABASE_BLOG
    value: main
    # Mongo chat
  - name: MONGODB_URL_CHAT
    value: mongodb+srv://jobhop:Qus7YbkpaqfIlwAI@mongodb-jobhop-prod.xbpov.mongodb.net
  - name: MONGODB_DATABASE_CHAT
    value: main
    # Mongo common
  - name: MONGODB_URL_COMMON
    value: mongodb+srv://jobhop:Qus7YbkpaqfIlwAI@mongodb-jobhop-prod.xbpov.mongodb.net
  - name: MONGODB_DATABASE_COMMON
    value: main
    # Mongo candidate
  - name: MONGODB_URL_CANDIDATE
    value: mongodb+srv://jobhop:Qus7YbkpaqfIlwAI@mongodb-jobhop-prod.xbpov.mongodb.net
  - name: MONGODB_DATABASE_CANDIDATE
    value: candidate
    # Mongo cv
  - name: MONGODB_URL_CV
    value: mongodb+srv://jobhop:Qus7YbkpaqfIlwAI@mongodb-jobhop-prod.xbpov.mongodb.net
  - name: MONGODB_DATABASE_CV
    value: cv
    # Mongo job
  - name: MONGODB_URL_JOB
    value: mongodb+srv://jobhop:Qus7YbkpaqfIlwAI@mongodb-jobhop-prod.xbpov.mongodb.net
  - name: MONGODB_DATABASE_JOB
    value: job
    # Mongo jobseeker
  - name: MONGODB_URL_JOBSEEKER
    value: mongodb+srv://jobhop:Qus7YbkpaqfIlwAI@mongodb-jobhop-prod.xbpov.mongodb.net
  - name: MONGODB_DATABASE_JOBSEEKER
    value: main
    # Mongo quizz
  - name: MONGODB_URL_QUIZZ
    value: mongodb+srv://jobhop:Qus7YbkpaqfIlwAI@mongodb-jobhop-prod.xbpov.mongodb.net
  - name: MONGODB_DATABASE_QUIZZ
    value: gamification
    # Mongo lucky spin
  - name: MONGODB_URL_LUCKY_SPIN
    value: mongodb+srv://jobhop:Qus7YbkpaqfIlwAI@mongodb-jobhop-prod.xbpov.mongodb.net
  - name: MONGODB_DATABASE_LUCKY_SPIN
    value: gamification
    # Mongo organization
  - name: MONGODB_URL_ORGANIZATION
    value: mongodb+srv://jobhop:Qus7YbkpaqfIlwAI@mongodb-jobhop-prod.xbpov.mongodb.net
  - name: MONGODB_DATABASE_ORGANIZATION
    value: organization
    # Mongo users
  - name: MONGODB_URL_USERS
    value: mongodb+srv://jobhop:Qus7YbkpaqfIlwAI@mongodb-jobhop-prod.xbpov.mongodb.net
  - name: MONGODB_DATABASE_USERS
    value: main
    # Mongo other
  - name: MONGODB_URL_OTHER
    value: mongodb+srv://jobhop:Qus7YbkpaqfIlwAI@mongodb-jobhop-prod.xbpov.mongodb.net
  - name: MONGODB_DATABASE_OTHER
    value: main

    # MySQL
  - name: MYSQL_HOST
    value: prod-db-replica.ccirbf8qc9wd.ap-southeast-1.rds.amazonaws.com
  - name: MYSQL_PORT
    value: "3306"
  - name: MYSQL_USERNAME
    value: prodbackend
  - name: MYSQL_PASSWORD
    value: vTgDcd9Tgh8DLhfZgeI
  - name: MYSQL_DATABASE
    value: jobhop_production

    # Kafka config
  - name: KAFKA_BROKER
    value: kafka-0.kafka-headless.data.svc.cluster.local:9093
  - name: DATABASE_SERVER_NAME
    value: jobhop_production_replica

    # Other config
  - name: SNAPSHOT_INSERT_PAGE_SIZE
    value: "100"

livenessProbe:
  path: /health

readinessProbe:
  path: /health

containerSecurityContext:
  enabled: false

podSecurityContext:
  enabled: false

ingress:
  enabled: true
  ingressClassName: alb
  pathType: Prefix
  hostname: migration-api.jobhopin.com
  path: /
  annotations:
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: jobhop-prod
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:921270714038:certificate/a49d249c-1c8a-4556-8c6e-e98426d37cbf
