fullnameOverride: migration-gateway

args: ["npm", "run", "start:prod"]

extraEnvVars:
  - name: JWT_TOKEN_SECRET
    value: JWTMrJobhopSecretKey
  - name: JWT_TOKEN_EXPIRES
    value: "30"

  - name: MIGRATION_VERSION
    value: 1.1.6

    # Mongo config
    # Mongo migration
  - name: MONGODB_URL_MIGRATION
    value: mongodb://root:kzJ29YYQ0auPWF2G@mongodb-0-external.data.svc.cluster.local
  - name: MONGODB_DATABASE_MIGRATION
    value: main
    # Mongo activity
  - name: MONGODB_URL_ACTIVITY
    value: mongodb://root:kzJ29YYQ0auPWF2G@mongodb-0-external.data.svc.cluster.local
  - name: MONGODB_DATABASE_ACTIVITY
    value: activity
    # Mongo blog
  - name: MONGODB_URL_BLOG
    value: mongodb://root:kzJ29YYQ0auPWF2G@mongodb-0-external.data.svc.cluster.local
  - name: MONGODB_DATABASE_BLOG
    value: main
    # Mongo chat
  - name: MONGODB_URL_CHAT
    value: mongodb://root:kzJ29YYQ0auPWF2G@mongodb-0-external.data.svc.cluster.local
  - name: MONGODB_DATABASE_CHAT
    value: main
    # Mongo common
  - name: MONGODB_URL_COMMON
    value: mongodb://root:kzJ29YYQ0auPWF2G@mongodb-0-external.data.svc.cluster.local
  - name: MONGODB_DATABASE_COMMON
    value: main
    # Mongo candidate
  - name: MONGODB_URL_CANDIDATE
    value: mongodb://root:kzJ29YYQ0auPWF2G@mongodb-0-external.data.svc.cluster.local
  - name: MONGODB_DATABASE_CANDIDATE
    value: candidate
    # Mongo cv
  - name: MONGODB_URL_CV
    value: mongodb://root:kzJ29YYQ0auPWF2G@mongodb-0-external.data.svc.cluster.local
  - name: MONGODB_DATABASE_CV
    value: cv
    # Mongo job
  - name: MONGODB_URL_JOB
    value: mongodb://root:kzJ29YYQ0auPWF2G@mongodb-0-external.data.svc.cluster.local
  - name: MONGODB_DATABASE_JOB
    value: job
    # Mongo jobseeker
  - name: MONGODB_URL_JOBSEEKER
    value: mongodb://root:kzJ29YYQ0auPWF2G@mongodb-0-external.data.svc.cluster.local
  - name: MONGODB_DATABASE_JOBSEEKER
    value: main
    # Mongo quizz
  - name: MONGODB_URL_QUIZZ
    value: mongodb://root:kzJ29YYQ0auPWF2G@mongodb-0-external.data.svc.cluster.local
  - name: MONGODB_DATABASE_QUIZZ
    value: gamification
    # Mongo lucky spin
  - name: MONGODB_URL_LUCKY_SPIN
    value: mongodb://root:kzJ29YYQ0auPWF2G@mongodb-0-external.data.svc.cluster.local
  - name: MONGODB_DATABASE_LUCKY_SPIN
    value: gamification
    # Mongo organization
  - name: MONGODB_URL_ORGANIZATION
    value: mongodb://root:kzJ29YYQ0auPWF2G@mongodb-0-external.data.svc.cluster.local
  - name: MONGODB_DATABASE_ORGANIZATION
    value: organization
    # Mongo users
  - name: MONGODB_URL_USERS
    value: mongodb://root:kzJ29YYQ0auPWF2G@mongodb-0-external.data.svc.cluster.local
  - name: MONGODB_DATABASE_USERS
    value: main
    # Mongo other
  - name: MONGODB_URL_OTHER
    value: mongodb://root:kzJ29YYQ0auPWF2G@mongodb-0-external.data.svc.cluster.local
  - name: MONGODB_DATABASE_OTHER
    value: main

    # MySQL
  - name: MYSQL_HOST
    value: staging-db-replica.cnkx3mfw6lyk.ap-southeast-1.rds.amazonaws.com
  - name: MYSQL_PORT
    value: "3306"
  - name: MYSQL_USERNAME
    value: backend
  - name: MYSQL_PASSWORD
    value: f6qsmx9ijez9xxb9
  - name: MYSQL_DATABASE
    value: jobhop_staging

    # Kafka config
  - name: KAFKA_BROKER
    value: kafka-0.kafka-headless.data.svc.cluster.local:9093
  - name: DATABASE_SERVER_NAME
    value: jobhop_staging_replica

    # Other config
  - name: SNAPSHOT_INSERT_PAGE_SIZE
    value: "100"

livenessProbe:
  path: /health

readinessProbe:
  path: /health

containerSecurityContext:
  enabled: false

podSecurityContext:
  enabled: false

ingress:
  enabled: true
  ingressClassName: alb
  pathType: Prefix
  hostname: migration-jobhop-staging.jobhopin.com
  path: /
  annotations:
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: jobhop-staging
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:496324956666:certificate/4fa5f0fc-4053-47db-8753-ff8682d24b5e
