image:
  repository: public.ecr.aws/f8d9n2r3/btg-service-node-14
  pullPolicy: IfNotPresent
  tag: 1.0.1

resources:
  limits:
    memory: "2048Mi"
    cpu: "2"
  requests:
    memory: "1024Mi"
    cpu: "1"

nodeSelector:
  node-type: crawler

servicePackage:
  name: ''
  version: ''

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

replicaCount: 1

podAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/port: '9010'

affinity: { }

tolerations: [ ]
