fullnameOverride: common-service

args: ['npm', 'run', 'start:prod']

extraEnvVars:
  - name: JWT_TOKEN_SECRET
    value: JWTMrJobhopSecretKey
  - name: JWT_TOKEN_EXPIRES
    value: '30'
  - name: COMMON_SERVICE_MONGODB_URL
    value: mongodb://main:StrongP%40ssword@mongodb-0-external.data.svc.cluster.local/main
  - name: COMMON_SERVICE_RABITMQ_URL
    value: amqp://jobhop_dev:h5x}N4p:FF8Q)+rj@rabbitmq.data.svc.cluster.local:5672
  - name: COMMON_SERVICE_RABITMQ_QUEUE
    value: common_queue
  - name: REDIS_HOST
    value: redis-master.data.svc.cluster.local  
  - name: REDIS_PASSWORD
    value: jC2qe6890UxcxPKv
  - name: REDIS_PORT
    value: '6379'
  - name: REDIS_TIMEOUT
    value: '3600'      
  - name: REDIS_USETLS
    value: 'false'  
  - name: ASSET_URL
    value: https://assets.jobhopin.com
  - name: DEFAULT_PAGE_SIZE
    value: '20'

nodeAffinityPreset:
  type: "hard"

livenessProbe:
  path: /health

readinessProbe:
  path: /health

containerSecurityContext:
  enabled: false

podSecurityContext:
  enabled: false
