fullnameOverride: quizz-service

args: ['npm', 'run', 'start:dev']

extraEnvVars:
  - name: JWT_TOKEN_SECRET
    value: JWTMrJobhopSecretKey
  - name: JWT_TOKEN_EXPIRES
    value: '30'
  - name: QUIZZ_SERVICE_MONGODB_URL
    value: mongodb://gamification:StrongP%40ssword@mongodb-0-external.data.svc.cluster.local/gamification
  - name: QUIZZ_SERVICE_RABITMQ_URL
    value: amqp://jobhop_dev:h5x}N4p:FF8Q)+rj@rabbitmq.data.svc.cluster.local:5672
  - name: QUIZZ_SERVICE_RABITMQ_QUEUE
    value: quizz_queue
  - name: AUTH_SERVICE_RABITMQ_URL
    value: amqp://jobhop_dev:h5x}N4p:FF8Q)+rj@rabbitmq.data.svc.cluster.local:5672
  - name: AUTH_SERVICE_RABITMQ_QUEUE
    value: auth_queue 
  - name: JOBSEEKER_SERVICE_RABITMQ_URL
    value: amqp://jobhop_dev:h5x}N4p:FF8Q)+rj@rabbitmq.data.svc.cluster.local:5672
  - name: JOBSEEKER_SERVICE_RABITMQ_QUEUE
    value: jobseeker_queue       
  - name: ASSET_URL
    value: https://assets.jobhopin.com
  - name: CDN_URL
    value: https://cdn-staging.jobhopin.com
  - name: DEFAULT_PAGE_SIZE
    value: '20'

nodeAffinityPreset:
  type: "hard"

livenessProbe:
  path: /health

readinessProbe:
  path: /health

containerSecurityContext:
  enabled: false

podSecurityContext:
  enabled: false
