fullnameOverride: quizz-service

replicaCount: 2

args: ['npm', 'run', 'start:prod']

extraEnvVars:
  - name: JWT_TOKEN_SECRET
    value: JWTMrJobhopSecretKey
  - name: JWT_TOKEN_EXPIRES
    value: '30'
  - name: QUIZZ_SERVICE_MONGODB_URL
    value: mongodb+srv://gamification:sKrErP8VIaXZa09Y@mongodb-jobhop-prod.xbpov.mongodb.net/gamification
  - name: QUIZZ_SERVICE_RABITMQ_URL
    value: amqp://jobhop_prod:JgpagP89Qw7DaKai@rabbitmq.data.svc.cluster.local:5672
  - name: QUIZZ_SERVICE_RABITMQ_QUEUE
    value: quizz_queue
  - name: AUTH_SERVICE_RABITMQ_URL
    value: amqp://jobhop_prod:JgpagP89Qw7DaKai@rabbitmq.data.svc.cluster.local:5672
  - name: AUTH_SERVICE_RABITMQ_QUEUE
    value: auth_queue 
  - name: JOBSEEKER_SERVICE_RABITMQ_URL
    value: amqp://jobhop_prod:JgpagP89Qw7DaKai@rabbitmq.data.svc.cluster.local:5672
  - name: JOBSEEKER_SERVICE_RABITMQ_QUEUE
    value: jobseeker_queue      
  - name: ASSET_URL
    value: https://assets.jobhopin.com
  - name: CDN_URL
    value: https://cdn.jobhopin.com
  - name: DEFAULT_PAGE_SIZE
    value: '20'

nodeAffinityPreset:
  type: "hard"

livenessProbe:
  path: /health

readinessProbe:
  path: /health

containerSecurityContext:
  enabled: false

podSecurityContext:
  enabled: false
