gateway:
  port: 9010

log:
  level: info
  logStash:
    host: 51.222.44.17
    port: 31658
    enable: false

mysql:
  host: mysql-jobhop-dev.jobhopin.com
  port: 3306
  user: jobhop_dev
  password: tDYidUDJscyoTM7W
  database: jobhop_dev
  connectTimeout: 20000

es:
  url: http://elasticsearch-jobhop-dev.jobhopin.com:9200
  maxRetries: 1
  requestTimeout: 60000
  pingTimeout: 60000
  sniffOnStart: true
