environment: development

envVariables:
  - name: LOG_LEVEL
    value: info
  - name: LOG_LOG_STASH_HOST
    value: 51.222.44.17
  - name: LOG_LOG_STASH_PORT
    value: "'31658'"
  - name: LOG_LOG_STASH_ENABLE
    value: "'false'"
  - name: MYSQL_HOST
    value: mysql-jobhop-dev.jobhopin.com
  - name: MYSQL_PORT
    value: "'3306'"
  - name: MYSQL_DATABASE
    value: jobhop_dev

ingress:
  enabled: true
  ingressClassName: alb
  pathType: Prefix
  hostname: admin-jobhop-dev.jobhopin.com
  path: /
  annotations:
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: jobhop-dev
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:730348852333:certificate/ba5bea70-b878-4596-ad40-f80721bd9bd0
